export const SET_USER = "SET_USER";
export const SET_IS_FETCHING_USER = "SET_IS_FETCHING_USER";
export const SET_HTTP_STATUS_FETCH_USER = "SET_HTTP_STATUS_FETCH_USER";

export const SET_USER_PERSONAL_REPOSITORIES = "SET_USER_PERSONAL_REPOSITORIES";
export const SET_IS_FETCHING_USER_PERSONAL_REPOSITORIES =
  "SET_IS_FETCHING_USER_PERSONAL_REPOSITORIES";

export const SET_USER_STARRED_REPOSITORIES = "SET_USER_STARRED_REPOSITORIES";
export const SET_IS_FETCHING_USER_STARRED_REPOSITORIES =
  "SET_IS_FETCHING_USER_STARRED_REPOSITORIES";

export const RESET_USER_DATA = "RESET_USER_DATA";

// Saga types

export const SAGA_FETCH_USER = "SAGA_FETCH_USER";
export const SAGA_FETCH_USER_PERSONAL_REPOSITORIES =
  "SAGA_FETCH_USER_PERSONAL_REPOSITORIES";
export const SAGA_FETCH_USER_STARRED_REPOSITORIES =
  "SAGA_FETCH_USER_STARRED_REPOSITORIES";
